{% set name = "textblob" %}
{% set version = "0.15.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "574f30be68a5afcc9f0ccfad088394833343a611c4f0a20473622e07c02cac0f" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - nltk >=3.1

test:
  imports:
    - textblob
    - textblob.en
    - textblob.unicodecsv

about:
  home: https://github.com/sloria/TextBlob
  license: MIT
  license_file: LICENSE
  summary: 'Simple, Pythonic text processing. Sentiment analysis, part-of-speech tagging, noun phrase parsing, and more.'
  license_family: MIT
  doc_url: https://textblob.readthedocs.io/en/dev/
  dev_url: https://github.com/sloria/TextBlob

extra:
  recipe-maintainers:
    - pmlandwehr
