{% set name = "textblob" %}
{% set version = "0.18.0.post0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8131c52c630bcdf61d04c359f939c98d5b836a01fba224d9e7ae22fc274e0ccb

build:
  number: 0
  skip: True  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
    - flit-core <4

  run:
    - python
    - nltk >=3.8


test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - textblob
    - textblob.en
    - textblob.unicodecsv
  commands:
    - pip check
    # Downloading nltk assets for testing. textblob.download corpora is insufficient for testing needs.
    - python -c "import nltk; nltk.download('punkt_tab')"
    - python -c "import nltk; nltk.download('averaged_perceptron_tagger_eng')"
    - python -m textblob.download_corpora
    - pytest -v tests
  requires:
    - pip
    - pytest
    # Adding numpy to test some of the classifying features of the library
    - numpy


about:
  home: https://github.com/sloria/TextBlob
  license: MIT
  license_file: LICENSE
  summary: 'Simple, Pythonic text processing. Sentiment analysis, part-of-speech tagging, noun phrase parsing, and more.'
  description: 'TextBlob is a Python library for processing textual data. It provides a simple API for diving into common
    natural language processing (NLP) tasks such as part-of-speech tagging, noun phrase extraction, sentiment analysis,
    classification, translation, and more.'
  license_family: MIT
  doc_url: https://textblob.readthedocs.io/en/dev/
  dev_url: https://github.com/sloria/TextBlob

extra:
  recipe-maintainers:
    - pmlandwehr
