{% set name = "textblob" %}
{% set version = "0.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sloria/TextBlob/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0fb422e903d8b640dc0d955ac79421b0a536d9c79ece11dbe238b9a60d8f48c3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - nltk >=3.9

test:
  source_files:
    - tests
  imports:
    - textblob
    - textblob._text
    - textblob.base
    - textblob.classifiers
    - textblob.decorators
    - textblob.en
    - textblob.en.inflect
    - textblob.en.np_extractors
    - textblob.en.parsers
    - textblob.en.sentiments
    - textblob.en.taggers
    - textblob.exceptions
    - textblob.formats
    - textblob.inflect
    - textblob.mixins
    - textblob.np_extractors
    - textblob.parsers
    - textblob.sentiments
    - textblob.taggers
    - textblob.tokenizers
    - textblob.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - numpy

about:
  home: https://github.com/sloria/TextBlob
  license: MIT AND BSD-2-Clause AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE
  summary: Simple, Pythonic text processing. Sentiment analysis, part-of-speech tagging, noun phrase parsing, and more.
  description: 'TextBlob is a Python library for processing textual data. It provides a simple API for diving into common::
    - natural language processing (NLP) tasks such as part-of-speech tagging, noun phrase extraction, sentiment analysis,
    - "classification, translation, and more.'
  license_family: OTHER
  doc_url: https://textblob.readthedocs.io/en/dev
  dev_url: https://github.com/sloria/TextBlob

extra:
  recipe-maintainers:
    - pmlandwehr