{% set name = "textblob" %}
{% set version = "0.15.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "7ff3c00cb5a85a30132ee6768b8c68cb2b9d76432fec18cd1b3ffe2f8594ec8c" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - nltk >=3.1

test:
  imports:
    - textblob
    - textblob.en
    - textblob.unicodecsv

about:
  home: https://github.com/sloria/TextBlob
  license: MIT
  license_file: LICENSE
  summary: 'Simple, Pythonic text processing. Sentiment analysis, part-of-speech tagging, noun phrase parsing, and more.'
  license_family: MIT
  doc_url: https://textblob.readthedocs.io/en/dev/
  dev_url: https://github.com/sloria/TextBlob

extra:
  recipe-maintainers:
    - pmlandwehr
