# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vLgU5TnX+NyyHiw+oPFPa6XQ1zxI3tzo32CrwLcRWC4bI4H2IHjynuesJdSi1BATgTZU1zUV0TAvluwIrXODmbGmE8PnEvYlWN32QFawCZE9CoUZhRWja2oWOH8XeJTLoaSdDChu5aZNIe/AgFmoWvkat87CzF5uYgkNPdUEw+HapvowrGPNmb+JaRsHdEBcdFbI1/8Cg01ez98i6u01n3hhdyQdGMz19QMdZyEr/tQHRtJRhfTOprzHzBWCPLmVJkleFlLkaU2e5Qke9+PuSntKnmlYTYDjsdHlmf01G+mje/CV/EUOIuHqf9lgdCb29i2zpcs2VdvkKA4OGw4dJHrjckzpHadtdem5IavmwQwpcNtQz7tcDi3QZwInHKKTrUaCcwl+43MjyefOybmOogpfix0Ak2Kc5XncargTLo4b0puren0TMLUB01VYhE4TpoJfIeXTNDpw9V2o3cU3nQKjwxF9xCAXNyPghtvvhLR3V8RUQDC2QyteEd8zTYQeZFYvwvjfEYwYu6ytwyMEFB9tOH/R0D8gmgM1xfw58NONHueX53DbAqyPJ/RtWimLBEZ3UlWvG0NM1lY/J30az+G4xfStZRW3F2QugU0O8HidKf+7Po9bNSYeH+EWEj764+3lzPW9LFHdN38HxTfxDg06yhfpx+ElPiKeGS67rMk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
