travis:
  secure:
    BINSTAR_TOKEN: fHJLs2HaWBBgMntDB6UoIkpGDrmIWaD8HsZW4lbrrbufiO9szRkrpTCcXLysWNLDI4B+BgUG45d1oXEAE3MaXDjRimbomu1azL5JO8Fs76Bz3w/W5sEeQd9bruR1zJYCHil2VUYp4zsJ11e6s2DHBV3Sza1X4M5Wk0thWaUIwzBtjf/HbCccc4UX/c3xi7ewbbaVSwaIE+5gZ9wK3dg+Y+giLoo1HXkqWS6MAAVyMKSC5BpZDVfsLyR7NCNFQjcrnaAb04r2M8GspOaj/rFQn6a5mpwqauBTaHRMWYiSUUty7Ct9ae2vQ1MLrk2U/sHR0ldbLWCQ1oRR/nkwVwPHFu/vGGt9BguFIxm6Ybapbhmav0BlrC10bd9kgtHH3qTmLks+HndB87yJZRJtCi3glV5fgIeYUykFXpAJ5ztBDDnEy+yvr0rlOWh0TPDbzGDzc3v8fu4UIrweG6EDyoiMmY9kQNApbsM5hPm5yQ36hr4a33XSHdfSEEOPFABa1lB34dIJdhd06E2tVZsCUqV2B/sSLqz2tR3W8yFAo9i4BGzGkcz9PZ1efB8gn46HhUKocF8txGwpD9W7qcENx+ytlRJvy1oniGeIoUjCRxXd5qNsE08oD7M/La8VoTyq1Z8O78VA3953a/OtRU0BpsI47QjyxZxSdZ+sv9Q05TZJ24I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
