travis:
  secure:
    BINSTAR_TOKEN: vLgU5TnX+NyyHiw+oPFPa6XQ1zxI3tzo32CrwLcRWC4bI4H2IHjynuesJdSi1BATgTZU1zUV0TAvluwIrXODmbGmE8PnEvYlWN32QFawCZE9CoUZhRWja2oWOH8XeJTLoaSdDChu5aZNIe/AgFmoWvkat87CzF5uYgkNPdUEw+HapvowrGPNmb+JaRsHdEBcdFbI1/8Cg01ez98i6u01n3hhdyQdGMz19QMdZyEr/tQHRtJRhfTOprzHzBWCPLmVJkleFlLkaU2e5Qke9+PuSntKnmlYTYDjsdHlmf01G+mje/CV/EUOIuHqf9lgdCb29i2zpcs2VdvkKA4OGw4dJHrjckzpHadtdem5IavmwQwpcNtQz7tcDi3QZwInHKKTrUaCcwl+43MjyefOybmOogpfix0Ak2Kc5XncargTLo4b0puren0TMLUB01VYhE4TpoJfIeXTNDpw9V2o3cU3nQKjwxF9xCAXNyPghtvvhLR3V8RUQDC2QyteEd8zTYQeZFYvwvjfEYwYu6ytwyMEFB9tOH/R0D8gmgM1xfw58NONHueX53DbAqyPJ/RtWimLBEZ3UlWvG0NM1lY/J30az+G4xfStZRW3F2QugU0O8HidKf+7Po9bNSYeH+EWEj764+3lzPW9LFHdN38HxTfxDg06yhfpx+ElPiKeGS67rMk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
