travis:
  secure:
    BINSTAR_TOKEN: aNTj9GjXycojM8lrxRllWFD4bbaj1M3g4whEi9L2aSwvbd6VT6E8bPEJ4GjrkmM+6UfctC1/kGOImBE1OVAcXNytlogGa4tuSfqwK6lE9UghBMd3lXdjqo6nN7Q7E3T/9FDpBDSPbHePFmQf5BBteUtmx3kzhrvDkvaJXVn5/C2NJxwnJWyfpHBVMg+fHckHw6eaQ3M0rKNv6dMH7xIrzN+hiLZjXJQ5j8+IBK1hG1IN4rIQroxDJApuMNo/MUpNTDHap5faz37qfXbRJ93Xr266tq9j5wr6VzQRqcyGQGxXe8kEI4Rt/a4MjHazoukzI7xLYUOVeJsaYFe76DeHEN1yK7V3e7IJwtd55yWJw9FakmjNEeFA1hdsqW/wolY22Sfz1sGl0EdBJh1iPVsZ9d2b1Bgg6RQqZKQKKGNLnDip+rOLaZUT5ueNL1K87B7ISHHlW+//7hNBIhWSxP3PA58JIbpqueMdXvQH8zRoHA0YXbcWFawsWnCa7CdF9ElECjYfjChIoYLQmJP3d8f3qauCCl5RWOQtPXJIa/xYvP76qF9Yo+WHPaHxqwn/UjO9xn5rTlwKdPMTeg3JjHIYHXfLboS4FfgLzktXPy0wuyw2SJMog98JVDW2aZz0V+haUFBdSPQRIm4kv6vS66XuWHzL8PjwBQl34Ppn+o48XjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
